[package]
name = "feo-boy"
version = "0.1.0"
authors = [
    "Andy Russell <arussell123@gmail.com>",
    "Andrew Fishberg <fishberg.github@gmail.com>",
    "Max Comstock <maxibillion6@gmail.com>",
]

[[bin]]
doc = false
name = "feo-boy"
path = "src/bin/feo-boy.rs"

[dependencies]
clap = "2"
error-chain = "0.10"
log = "0.3"
