[package]
name = "feo-boy"
version = "0.1.0"
authors = [
    "Andy Russell <arussell123@gmail.com>",
    "Andrew Fishberg <fishberg.github@gmail.com>",
    "Max Comstock <maxibillion6@gmail.com>",
]

[[bin]]
doc = false
name = "feo-boy"
path = "src/bin/feo-boy.rs"

[dependencies]
byteorder = "1"
clap = "2"
error-chain = "0.10"
env_logger = "0.4"
itertools = "0.6"
log = "0.3"
lazy_static = "0.2"
